/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.MotoristasDAO;
import entidade.Motoristas;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author engenharia06
 */
public class MotoristasView extends javax.swing.JPanel {

    /**
     * Creates new form MotoristasView
     */
    public MotoristasView(boolean permissao) {
        initComponents();
        
        refreshTable(permissao);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        txtCPF1 = new javax.swing.JFormattedTextField();
        txtCNH1 = new javax.swing.JTextField();
        cbCategoria1 = new javax.swing.JComboBox<>();
        txtValidade1 = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        btnCadastrar1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnExcluir1 = new javax.swing.JButton();
        btnLimpar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMotoristas1 = new javax.swing.JTable();

        jLabel6.setText("Nome:");

        jLabel7.setText("CPF:");

        jLabel8.setText("CNH:");

        jLabel9.setText("Categoria:");

        jLabel10.setText("Validade:");

        try {
            txtCPF1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cbCategoria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "C", "D" }));

        try {
            txtValidade1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCNH1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCPF1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNome1))
                .addGap(8, 8, 8))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCNH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtValidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCadastrar1.setText("Cadastrar");
        btnCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar1ActionPerformed(evt);
            }
        });

        btnEditar1.setText("Editar");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        btnExcluir1.setText("Excluir");
        btnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir1ActionPerformed(evt);
            }
        });

        btnLimpar1.setText("Limpar");
        btnLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadastrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar1)
                    .addComponent(btnExcluir1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar1)
                    .addComponent(btnLimpar1))
                .addGap(24, 24, 24))
        );

        tblMotoristas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "CNH", "Categoria", "Validade"
            }
        ));
        jScrollPane2.setViewportView(tblMotoristas1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //Metodo para atualizacao da tabela
    public void refreshTable (boolean permissao) {
        if (permissao == false) {
            btnCadastrar1.setEnabled(false);
            btnEditar1.setEnabled(false);
            btnExcluir1.setEnabled(false);
            btnLimpar1.setEnabled(false);
        }
        
        ArrayList<Motoristas> list = new ArrayList();
        
        //realiza a consulta
        list = new MotoristasDAO().consultarTodos();

        int numLinhas = tblMotoristas1.getRowCount();

        //verifica se a tabela precisa ser maior
        //if (numLinhas < list.size()) {
        //    tblVeiculos.insertRow();
        //}
        
        //deleta os dados antigos da tabela
        for (int i = 0; i < numLinhas; i++) {
            tblMotoristas1.setValueAt(null, i, 0);
            tblMotoristas1.setValueAt(null, i, 1);
            tblMotoristas1.setValueAt(null, i, 2);
            tblMotoristas1.setValueAt(null, i, 3);
            tblMotoristas1.setValueAt(null, i, 4);
        }

        //Imprime no console e muda o valor na tabela
        for (int i = 0; i < list.size(); i++) {
            Motoristas obj = Motoristas.class.cast(list.get(i));
            
            tblMotoristas1.setValueAt(obj.getNome(), i, 0);
            tblMotoristas1.setValueAt(obj.getCpf(), i, 1);
            tblMotoristas1.setValueAt(obj.getCnh(), i, 2);
            tblMotoristas1.setValueAt(obj.getCategoriaCnh(), i, 3);
            tblMotoristas1.setValueAt(obj.getValidadeCnh(), i, 4);
        }
    }
    
    private void btnCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar1ActionPerformed
        try {
            //pega o texto da janela do formulario
            String nome = txtNome1.getText();
            String cpf = txtCPF1.getText();
            String cnh = txtCNH1.getText();
            String categoria_cnh = cbCategoria1.getSelectedItem().toString();
            String validade_cnh = txtValidade1.getText();

            Motoristas obj = new Motoristas();
            obj.setNome(nome);
            obj.setCpf(cpf);
            obj.setCnh(cnh);
            obj.setCategoriaCnh(categoria_cnh);
            obj.setValidadeCnh(validade_cnh);
            
            // criacao do obj DAO
            MotoristasDAO DAO = new MotoristasDAO();

            if (DAO.salvar(obj) == null) {
                JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");

                //atualiza tabela
                refreshTable(true);
            } else {
                JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
            }
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
        }
    }//GEN-LAST:event_btnCadastrar1ActionPerformed

    private void btnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir1ActionPerformed
        int id = -1;

        //pega a linha da tabela selecionada e extrai a placa
        int linha = tblMotoristas1.getSelectedRow();
        String login = tblMotoristas1.getValueAt(linha, 1).toString();
        
        //pega todos objetos da classe e pesquisa qual tem a msm placa
        ArrayList<Motoristas> list = new ArrayList();
        // criacao do obj DAO
        MotoristasDAO DAO = new MotoristasDAO();
        
        //realiza a consulta
        list = new MotoristasDAO().consultarTodos();
        
        //pega o id do objeto
        for (int i = 0; i < list.size(); i++){
            String searchCpf = list.get(i).getCpf();
            
            if (login.equals(searchCpf)) {
                id = list.get(i).getIdMotorista();
                break;
            }
            else{}
        }
        
        var result = DAO.excluir(id);
        
        if (id == -1) {
            JOptionPane.showMessageDialog(this, "ERRO!");
        
        }    else if (result == null) {
            JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");
            
        }   else if (result.contains("SQLIntegrityConstraintViolationException") == true) {
            JOptionPane.showMessageDialog(this, "Exclusão é impossível, item faz parte de uma entrega.");
        
        }    else {
            JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
        }
    }//GEN-LAST:event_btnExcluir1ActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        String isRight = null;

        //pega todos os ids
        ArrayList<Motoristas> list = new ArrayList();
        list = new MotoristasDAO().consultarTodos();
        
        //loop pra pegar e salvar todas alteracoes na tabela
        for (int i = 0;i < list.size(); i++) {
            int id = list.get(i).getIdMotorista();
            String nome = tblMotoristas1.getValueAt(i, 0).toString();
            String cpf = tblMotoristas1.getValueAt(i, 1).toString();
            String cnh = tblMotoristas1.getValueAt(i, 2).toString();
            String categoria_cnh = tblMotoristas1.getValueAt(i, 3).toString();
            String validade_cnh = tblMotoristas1.getValueAt(i, 4).toString();

            // cricao obj
            Motoristas obj = new Motoristas();
            obj.setIdMotorista(id);
            obj.setNome(nome);
            obj.setCpf(cpf);
            obj.setCnh(cnh);
            obj.setCategoriaCnh(categoria_cnh);
            obj.setValidadeCnh(validade_cnh);

            // criacao do obj DAO
            MotoristasDAO DAO = new MotoristasDAO();

            isRight = DAO.atualizar(obj);
        }
        
        if (isRight == null) {
            JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!");

        } else {
            JOptionPane.showMessageDialog(this, "Problemas ao salvar registro!");
        }
        
        refreshTable(true);
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpar1ActionPerformed
        txtNome1.setText("");
        txtCPF1.setText("");
        txtCNH1.setText("");
        txtValidade1.setText("");
    }//GEN-LAST:event_btnLimpar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar1;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnExcluir1;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JComboBox<String> cbCategoria1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMotoristas1;
    private javax.swing.JTextField txtCNH1;
    private javax.swing.JFormattedTextField txtCPF1;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JFormattedTextField txtValidade1;
    // End of variables declaration//GEN-END:variables
}
