/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import apoio.ConexaoMySQL;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author engenharia06
 */
public class RelatoriosView extends javax.swing.JPanel {

    /**
     * Creates new form RelatoriosView
     */
    public RelatoriosView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbTipoRelatorio = new javax.swing.JComboBox<>();
        btnGerarRelatorio = new javax.swing.JButton();
        scrollRelatorio = new javax.swing.JScrollPane();
        txtRelatorio = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Selecione um Relatório:");

        cbTipoRelatorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veículos", "Motoristas", "Entregas" }));
        cbTipoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoRelatorioActionPerformed(evt);
            }
        });

        btnGerarRelatorio.setText("Gerar Relatório");
        btnGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarRelatorioActionPerformed(evt);
            }
        });

        txtRelatorio.setColumns(20);
        txtRelatorio.setRows(5);
        scrollRelatorio.setViewportView(txtRelatorio);

        jButton1.setText("Exportar PDF");

        jButton2.setText("Limpar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTipoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGerarRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
            .addComponent(scrollRelatorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTipoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerarRelatorio)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarRelatorioActionPerformed
        String tipo = cbTipoRelatorio.getSelectedItem().toString();
        txtRelatorio.setText("");
        

        try{
            Statement st = ConexaoMySQL.getInstance().getConnection().createStatement();

            switch (tipo) {
                case "Veículos":
                    String sql_veiculos = "SELECT placa, modelo, status FROM veiculos";
                    
                    ResultSet retorno_veiculos = st.executeQuery(sql_veiculos);
                    txtRelatorio.append("RELATÓRIO DE VEÍCULOS:\n\n");
                    while (retorno_veiculos.next()) {
                        txtRelatorio.append(String.format("Placa: %s | Modelo: %s | Status: %s\n",
                            retorno_veiculos.getString("placa"),
                            retorno_veiculos.getString("modelo"),
                            retorno_veiculos.getString("status")));
                    }
                    break;

                case "Motoristas":
                    String sql_motoristas = "SELECT nome, cnh, validade_cnh FROM motoristas";
                    
                    ResultSet retorno_motoristas = st.executeQuery(sql_motoristas);
                    txtRelatorio.append("RELATÓRIO DE MOTORISTAS:\n\n");
                    while (retorno_motoristas.next()) {
                        txtRelatorio.append(String.format("Nome: %s | CNH: %s | Validade: %s\n",
                            retorno_motoristas.getString("nome"),
                            retorno_motoristas.getString("cnh"),
                            retorno_motoristas.getDate("validade_cnh")));
                    }
                    break;

                case "Entregas":
                    String sql_entregas = "SELECT codigo, destino, status FROM entregas";
                    
                    ResultSet retorno_entregas = st.executeQuery(sql_entregas);
                    txtRelatorio.append("RELATÓRIO DE ENTREGAS:\n\n");
                    while (retorno_entregas.next()) {
                        txtRelatorio.append(String.format("Código: %s | Destino: %s | Status: %s\n",
                            retorno_entregas.getString("codigo"),
                            retorno_entregas.getString("destino"),
                            retorno_entregas.getString("status")));
                    }
                    break;

                default:
                    txtRelatorio.setText("Selecione um tipo válido de relatório.");
            }

        } catch (Exception e) {
            System.out.println("Erro ao consultar base de dados: " + e);
        }
    }//GEN-LAST:event_btnGerarRelatorioActionPerformed

    private void cbTipoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoRelatorioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarRelatorio;
    private javax.swing.JComboBox<String> cbTipoRelatorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scrollRelatorio;
    private javax.swing.JTextArea txtRelatorio;
    // End of variables declaration//GEN-END:variables
}
